[versions]
# ---- The ExoQuery plugin version that will be released! ----
pluginVersion    = "2.0.0.PL"
# ---- The Terpal Controller Version ----
controller       = "4.4.0"
# ---- All the other versions used ----
terpal           = "2.2.20-2.0.1.PL"
kotlin           = "2.2.20"
ksp              = "2.2.20-2.0.3"
serialization    = "1.7.3"
coroutines       = "1.8.1"
kotlinx-datetime = "0.6.0"
gradle           = "9.2.1"
nexus-publish    = "1.1.0"
dokka            = "1.9.20"
android-gradle   = "8.2.0"
decomat          = "1.0.0"
pprint           = "3.0.0"
kotest           = "6.0.3"
jackson          = "2.17.0"
sql-formatter    = "2.0.4"
jb-annotations   = "26.0.2"
koog             = "0.3.0"
buildconfig      = "3.1.0"
gradle-publish   = "1.1.0"
mapdb            = "3.1.0"
auto-service     = "1.0.1"
androidx-room    = "2.7.1"
androidx-sqlite  = "2.4.0"
androidx-test    = "1.6.1"
androidx-test-junit = "1.1.3"
androidx-test-espresso = "3.4.0"
robolectric      = "4.13"
sqldelight       = "2.0.2"
hikaricp         = "5.0.1"
typesafe-config  = "1.4.1"
embedded-postgres = "2.0.7"
embedded-postgres-binaries = "16.2.0"
mysql-connector  = "8.0.29"
mssql-jdbc       = "7.4.1.jre11"
h2               = "2.2.224"
oracle-ojdbc     = "19.3.0.0"
sqlite-jdbc      = "3.42.0.1"
flyway           = "7.15.0"
exposed          = "0.60.0"
postgresql       = "42.7.3"
kctfork          = "0.11.0"

[libraries]
kotlin-gradle-plugin               = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compiler-embeddable         = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinx-coroutines-core            = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json         = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-core         = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-protobuf     = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlinx-datetime                   = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
dokka-gradle-plugin                = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
nexus-publish-plugin               = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish" }
controller-android                 = { module = "io.exoquery:controller-android", version.ref = "controller" }
controller-core                    = { module = "io.exoquery:controller-core", version.ref = "controller" }
controller-jdbc                    = { module = "io.exoquery:controller-jdbc", version.ref = "controller" }
controller-native                  = { module = "io.exoquery:controller-native", version.ref = "controller" }
controller-r2dbc                   = { module = "io.exoquery:controller-r2dbc", version.ref = "controller" }
decomat-core                       = { module = "io.exoquery:decomat-core", version.ref = "decomat" }
decomat-ksp                        = { module = "io.exoquery:decomat-ksp", version.ref = "decomat" }
terpal-runtime                     = { module = "io.exoquery:terpal-runtime", version.ref = "terpal" }
pprint-kotlin-kmp                  = { module = "io.exoquery:pprint-kotlin-kmp", version.ref = "pprint" }
pprint-kotlin                      = { module = "io.exoquery:pprint-kotlin", version.ref = "pprint" }
kotest-framework                   = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions                  = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5               = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-engine            = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
jackson-module-kotlin              = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
sql-formatter                      = { module = "com.github.vertical-blank:sql-formatter", version.ref = "sql-formatter" }
jb-annotations                     = { module = "org.jetbrains:annotations", version.ref = "jb-annotations" }
koog-agents                        = { module = "ai.koog:koog-agents", version.ref = "koog" }
mapdb                              = { module = "org.mapdb:mapdb", version.ref = "mapdb" }
auto-service                       = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
auto-service-annotations           = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
androidx-room-runtime              = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx                  = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-sqlite-framework          = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidx-sqlite" }
androidx-test-core                 = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner               = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-junit                = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso-core        = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
robolectric                        = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
sqldelight-android-driver          = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver           = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
hikaricp                           = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
typesafe-config                    = { module = "com.typesafe:config", version.ref = "typesafe-config" }
embedded-postgres                  = { module = "io.zonky.test:embedded-postgres", version.ref = "embedded-postgres" }
embedded-postgres-binaries         = { module = "io.zonky.test.postgres:embedded-postgres-binaries-linux-amd64", version.ref = "embedded-postgres-binaries" }
mysql-connector-java               = { module = "mysql:mysql-connector-java", version.ref = "mysql-connector" }
mssql-jdbc                         = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssql-jdbc" }
h2                                 = { module = "com.h2database:h2", version.ref = "h2" }
oracle-ojdbc8                      = { module = "com.oracle.ojdbc:ojdbc8", version.ref = "oracle-ojdbc" }
sqlite-jdbc                        = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
flyway-core                        = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
exposed-core                       = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao                        = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc                       = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
postgresql                         = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
kctfork-core                       = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }

[plugins]
kotlin-jvm                        = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform              = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kapt                       = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinx-serialization             = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                               = { id = "com.google.devtools.ksp", version.ref = "ksp" }
terpal                            = { id = "io.exoquery.terpal-plugin", version.ref = "terpal" }
kotest                            = { id = "io.kotest", version.ref = "kotest" }
gradle-plugin-publish             = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
buildconfig                       = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
androidx-room                     = { id = "androidx.room", version.ref = "androidx-room" }
android-library                   = { id = "com.android.library", version.ref = "android-gradle" }
dokka                             = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish                     = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
