name: CI

# Was also `push`, but now only runs on PRs since we don't want build twice
on: [ pull_request ]

permissions:
  contents: read       # Only need to read repository contents
  pull-requests: write # Needed to add annotations to PRs
  checks: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      # I.e. the presence of this step means that overriding a golden file, not testing against it
      - name: Validate No ExoGoldenOverride Instances
        if: matrix.os == 'ubuntu-latest' # Windows container does not like this grep. Only need to run it once for the codebase anyway
        uses: freckle/grep-action@dd64f200665b77673185885bd2ef9e72bbd9ecd9
        with:
          # Look for the exact text FORBIDDEN_STRING anywhere in the PR diff
          patterns: |
            - pattern: "Mode.ExoGoldenOverride()"
              syntax: fixed          # plain text search; use "extended" for regex
              level: failure
              title: Presence of Mode.ExoGoldenOverride() Detected
              message: |
                Please remove every occurrence of the Mode.ExoGoldenOverride() before merging.
          only-changed: false

      - name: 'Run Jdbc, Android, and Native-Linux Tests'
        if: matrix.os == 'ubuntu-latest'
        run: >-
          docker compose build && docker compose run --rm --service-ports setup &&
          ./gradlew build --stacktrace -PisCI -Pnosign

      - name: 'Run MacOS Tests'
        if: matrix.os == 'macOS-latest'
        run: ./gradlew :exoquery-runner-native:build --stacktrace -PisCI -Pnosign

      - name: 'Run windows tests'
        if: matrix.os == 'windows-latest'
        run: ./gradlew :exoquery-runner-native:mingwX64Test --stacktrace -PisCI -Pnosign
